# Generated by Django 6.0 on 2026-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(default='Arrays', max_length=50),
        ),
    ]
