# Generated by Django 6.0.2 on 2026-04-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dsa', 'DSA'), ('sql', 'SQL')], max_length=5)),
                ('content_data', models.JSONField()),
            ],
        ),
    ]
